spring:
  application:
    name: ts-voc-back

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PW}
      connection-test-query: SELECT 1

server:
  servlet:
    session:
      timeout: 90m